import React from 'react'
import figma from '@figma/code-connect'
import TextInput from './TextInput'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(TextInput, 'https://www.figma.com/design/ieK3h0I8pVv7tRUoR3z4Hh?node-id=15341-46504', {
  props: {
    textInput: figma.nestedProps('Text Input/placeholder', {
      label: figma.textContent('Label'),
    }),
    inputTextDisabled: figma.instance('inputTextDisabled'),
    trailingActionDisabled: figma.instance('trailingActionDisabled'),
    inputTextType: figma.instance('inputTextType'),
    hasLabel: figma.boolean('label?'),
    trailingAction: figma.instance('trailingAction'),
    hasTrailingAction: figma.boolean('➡️ trailingAction?'),
    icon: figma.instance('icon'),
    leadingVisual: figma.boolean('⬅️ leadingVisual?'),
    caption: figma.boolean('caption?', {
      false: undefined,
      true: figma.children(['_Caption']),
    }),
    size: figma.enum('size', {
      small: 'small',
      medium: 'medium',
      large: 'large',
    }),
    state: figma.enum('state', {
      rest: 'rest',
      focus: 'focus',
      disabled: 'disabled',
      'read-only': 'read-only',
    }),
    inset: figma.boolean('inset?'),
    label: figma.children(['Label']),
    validation: figma.children('Form.Validation'),
  },
  example: ({textInput, label, size, validation, caption}) => (
    // TextInput and FormControl.Label must be direct children of FormControl
    <>
      {label}
      <TextInput size={size} value={textInput.label} />
      {validation}
      {caption}
    </>
  ),
})
