import React from 'react'
import {ProgressBar, Item as ProgressBarItem} from './ProgressBar'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(ProgressBar, 'https://www.figma.com/design/ieK3h0I8pVv7tRUoR3z4Hh?node-id=16443-62464', {
  props: {
    size: figma.enum('size', {
      small: 'small',
      medium: 'default',
      large: 'large',
    }),
    children: figma.children(['_ProgressBar.item', '_ProgressBar.item', '_ProgressBar.item']),
  },
  example: ({size, children}) => (
    <ProgressBar barSize={size} progress="...">
      {children}
    </ProgressBar>
  ),
})

figma.connect(ProgressBarItem, 'https://www.figma.com/design/ieK3h0I8pVv7tRUoR3z4Hh?node-id=34334-68158', {
  props: {
    color: figma.enum('color', {
      green: {color: 'var(--data-green-color)'},
      teal: {color: 'var(--data-teal-color)'},
      blue: {color: 'var(--data-blue-color)'},
      purple: {color: 'var(--data-purple-color)'},
      orange: {color: 'var(--data-orange-color)'},
      red: {color: 'var(--data-red-color)'},
      pink: {color: 'var(--data-pink-color)'},
      yellow: {color: 'var(--data-yellow-color)'},
      auburn: {color: 'var(--data-auburn-color)'},
      gray: {color: 'var(--data-gray-color)'},
    }),
  },
  example: ({color}) => <ProgressBarItem sx={color} />,
})
