import React from 'react'
import Link from './Link'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Link, 'https://www.figma.com/design/ieK3h0I8pVv7tRUoR3z4Hh?node-id=20953-78768', {
  props: {
    label: figma.string('label'),
    trailingVisual: figma.boolean('trailingVisual?', {
      true: figma.instance('trailingVisual'),
      false: undefined,
    }),
    leadingVisual: figma.boolean('leadingVisual?', {
      true: figma.instance('leadingVisual'),
      false: undefined,
    }),
    muted: figma.enum('variant', {
      'text muted': true,
    }),
  },
  example: ({label, muted, leadingVisual, trailingVisual}) => (
    <Link inline muted={muted} href="#">
      {leadingVisual}
      {label}
      {trailingVisual}
    </Link>
  ),
})
