import React from 'react'
import Textarea from './Textarea'
import figma from '@figma/code-connect'
import FormControl from '../FormControl'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Textarea, 'https://www.figma.com/design/ieK3h0I8pVv7tRUoR3z4Hh?node-id=30948-151237', {
  props: {
    contrast: figma.boolean('contrast'),
    label: figma.boolean('label?', {true: figma.children('Label'), false: undefined}),
    caption: figma.boolean('caption?', {true: figma.children('Caption'), false: undefined}),
    state: figma.enum('state', {
      default: 'default',
      focus: 'focus',
      disabled: 'disabled',
    }),
    value: figma.enum('text type', {
      Value: figma.string('text'),
      Placeholder: undefined,
    }),
    placeholder: figma.enum('text type', {
      Value: 'Placeholder...',
      Placeholder: figma.string('text'),
    }),
    validation: figma.children('Form.Validation'),
  },
  example: ({label, caption, validation, ...props}) => (
    // Textarea and FormControl.Label must be direct children of FormControl
    <>
      {label}
      <Textarea {...props} />
      {validation}
      {caption}
    </>
  ),
})
